### ISSUE TITLE
16.1.json?

### ISSUE THREAD

**Issue by famod** [ccouzens/keycloak-openapi#16]
Is 16.0.json compatible with [Keycloak 16.1.0](https://www.keycloak.org/2021/12/keycloak-1610-released) or do we need a `16.1.json` for that?

If 16.1.json is required, please provide it and please also provide the "patched" variant (see also #15).

Thanks a lot!

**Comment by ccouzens** [comment]
I've added 16.1 to the `Makefile` and [generated it](https://github.com/ccouzens/keycloak-openapi/blob/main/keycloak/16.1.json).

> Is 16.0.json compatible with Keycloak 16.1.0

The generated JSON and YML files are identical to 16.0, so it should be compatible.

> please also provide the "patched" variant (see also #15).

The patched variant is a lot more effort for me to provide. I'll write more on that issue.

Thanks for using these OpenAPI definitions :)

**Comment by famod** [comment]
> The patched variant is a lot more effort for me to provide. I'll write more on that issue.

Thanks a lot! I'm very busy myself but this topic is rather high on my list, so please do let me know if I can help.

> Thanks for using these OpenAPI definitions :)

Thank _you_ for providing them! 👍

**Comment by ccouzens** [comment]
> I'm very busy myself but this topic is rather high on my list, so please do let me know if I can help.

I think this is a good workflow for making a patched version:

1. Start with the generated version and make a copy of it (`cp keycloak/16.0.json keycloak/16.0-patched.json`)
2. Think of functionality that you know is missing and would be useful to you
   1. Look to see if it exists in a previous version- if so, copy it from the previous version and make any updates required
   2. If it doesn't exist in an old version, then it will require more manual work
3. Repeat step 2 until everything you *need* is there.
 
Don't try and do everything - it will be too much work and take too much time. By only doing the bits that you use it is less likely to contain bugs (because you'd notice them in your program).

I recommend you only do the endpoints, query parameters and JSON payload properties that you need.

No worries if you don't get around to this 🙂
