### ISSUE TITLE
Remove Default from tagging

### ISSUE THREAD

**Issue by yordis** [ccouzens/keycloak-openapi#3]
Related to https://github.com/ccouzens/keycloak-openapi/issues/2

1. Visit https://petstore.swagger.io/
2. Enter `https://raw.githubusercontent.com/ccouzens/keycloak-openapi/master/keycloak/10.0.json` in the explore input field
3. Notice that the `Default` tag is duplicating the content.

I would propose to remove `Default` from the tagging, otherwise, it will generate duplicates in the swagger configuration, and I am not sure what is the value-added since every single operation has `Default` in it (unless I am missed something and I may be wrong)

**Comment by ccouzens** [comment]
Hi @yordis,

I'm torn about this one.

Here's a [commit](https://github.com/ccouzens/keycloak-openapi/commit/f59c2f28eda561b50714afe8290fc8dbfd48127d#diff-fed9d2390f98df5e3edf745fc58527e3) to show the problem.

The issue is that the example app had to be changed to avoid breaking. If I push this change to master, I might break other people's applications.

I will think about this, and make a decision tomorrow.

I wish I knew how people were using this project. It would help me understand if this would cause problems or not.

**Comment by yordis** [comment]
Personally, I dont mind breaking changes as long as the authors take the time to document the issue and how to potentially fix it.

This is a small fix that will pay off in the long term, especially that code-gen tools don't have to worry about such thing.

And better sooner than later.

**Comment by ccouzens** [comment]
I agree with what you say, and have pushed the change to master.

I've added a "Notable Changes" section to the readme to warn about the change
https://github.com/ccouzens/keycloak-openapi/blob/master/README.md#notable-changes
Hopefully this will be sufficient to warn existing users.
